
server:
  port: 8084

spring:
  application:
    name: spring-cloud-stream-rabbitmq-consumer
  rabbitmq:
    host: 192.168.163.41
    port: 5672
    username: admin
    password: 123456
    virtual-host: /dev
  cloud:
    stream:
      bindings:
        orderInputChannel:
          # 对应 RabbitMQ 的交换器
          destination: order-exchange
          # 对应 RabbitMQ 的队列，指定名称则会单播分发；若不设置，则默认会随机计算一个队列名，实现消息多播分发
          group: order-test-queue
        cacheInputChannel:
          # 对应 RabbitMQ 的交换器
          destination: cache-exchange
      rabbit:
        bindings:
          orderInputChannel:
            consumer:
              auto-bind-dlq: true
              republish-to-dlq: true