
server:
  port: 8083

spring:
  application:
    name: spring-cloud-stream-rabbitmq-consumer
  rabbitmq:
    host: 192.168.163.21
    port: 5672
    username: admin
    password: 123456
    virtual-host: /dev
  cloud:
    stream:
      bindings:
        orderInputChannel:
          # 对应 RabbitMQ 的交换器
          destination: order-exchange
          # 对应 RabbitMQ 的队列，指定名称则会单播分发；若不设置，则默认会随机计算一个队列名，实现消息多播分发
          group: order-queue
          consumer:
            # 禁用重试，默认为3
            max-attempts: 1
        cacheInputChannel:
          # 对应 RabbitMQ 的交换器
          destination: cache-exchange
      rabbit:
        bindings:
          orderInputChannel:
            consumer:
              # 开启死信队列，可以通过 RabbitMQ 控制台执行 Move messages 到正常队列，使其重新消费
              auto-bind-dlq: true
              # 消息放入死信队列时同时记录错误信息，启用此配置后，requeue-rejected 将无效
              republish-to-dlq: true
              # 死信交换器
              dead-letter-exchange: order-exchange-dlx
              # 失败的消息将会被重新提交到同一个 handler 进行处理，直到 handler 抛出 AmqpRejectAndDontRequeueException 异常为止
              requeue-rejected: true