
server:
  port: 7081

spring:
  application:
    name: spring-cloud-stream-rabbitmq-producer
  rabbitmq:
    host: 10.113.248.209
    port: 5672
    username: admin
    password: admin
    virtual-host: /dev
  cloud:
    stream:
      bindings:
        stringOutputChannel:
          # 对应 RabbitMQ 的交换器
          destination: string-exchange
        orderOutputChannel:
          # 对应 RabbitMQ 的交换器
          destination: order-exchange
        cacheOutputChannel:
          # 对应 RabbitMQ 的交换器
          destination: cache-exchange
        cacheInputChannel:
          # 对应 RabbitMQ 的交换器
          destination: cache-exchange